# Generated by Django 5.2.4 on 2025-07-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
