# Generated by Django 5.2.4 on 2025-07-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
